# Generated by Django 4.0.6 on 2022-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_new_post_date_new_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
