# Generated by Django 4.0.6 on 2022-09-19 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_followers_user_following_delete_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
