# Generated by Django 4.0.6 on 2022-09-19 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_new_post_u_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_post',
            name='u_likes',
        ),
        migrations.AddField(
            model_name='new_post',
            name='u_likes',
            field=models.ManyToManyField(blank=True, related_name='u_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
