# Generated by Django 4.1 on 2022-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_new_post_u_likes_new_post_u_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
